apiVersion: v1
kind: Service
metadata:
  name: myapp-service-deployment
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30009
  selector:
    app: myapp
    type: front-end
    